export const popularRepos = [
  { name: 'react', owner: 'facebook', stars: '203k', description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.' },
  { name: 'vue', owner: 'vuejs', stars: '203k', description: 'Vue.js is a progressive, incrementally-adoptable JavaScript framework.' },
  { name: 'tensorflow', owner: 'tensorflow', stars: '177k', description: 'An Open Source Machine Learning Framework for Everyone' },
  { name: 'vscode', owner: 'microsoft', stars: '154k', description: 'Visual Studio Code' },
  { name: 'linux', owner: 'torvalds', stars: '154k', description: 'Linux kernel source tree' },
  { name: 'kubernetes', owner: 'kubernetes', stars: '102k', description: 'Production-Grade Container Scheduling and Management' },
  { name: 'typescript', owner: 'microsoft', stars: '94k', description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.' },
  { name: 'rust', owner: 'rust-lang', stars: '87k', description: 'Empowering everyone to build reliable and efficient software.' },
  { name: 'go', owner: 'golang', stars: '114k', description: 'The Go programming language' },
  { name: 'node', owner: 'nodejs', stars: '98k', description: 'Node.js JavaScript runtime' },
  { name: 'deno', owner: 'denoland', stars: '89k', description: 'A modern runtime for JavaScript and TypeScript.' },
  { name: 'next.js', owner: 'vercel', stars: '112k', description: 'The React Framework for Production' },
  { name: 'flutter', owner: 'flutter', stars: '156k', description: 'Flutter makes it easy and fast to build beautiful apps for mobile and beyond' },
  { name: 'swift', owner: 'apple', stars: '63k', description: 'The Swift Programming Language' },
  { name: 'pytorch', owner: 'pytorch', stars: '71k', description: 'Tensors and Dynamic neural networks in Python' },
  { name: 'svelte', owner: 'sveltejs', stars: '73k', description: 'Cybernetically enhanced web apps' },
  { name: 'freeCodeCamp', owner: 'freeCodeCamp', stars: '378k', description: 'freeCodeCamp.org\'s open-source codebase and curriculum. Learn to code for free.' },
  { name: '996.ICU', owner: '996icu', stars: '268k', description: 'Repo for counting stars and contributing to Protests against 996 working hours of Chinese IT companies' },
  { name: 'free-programming-books', owner: 'EbookFoundation', stars: '289k', description: 'Freely available programming books' },
  { name: 'coding-interview-university', owner: 'jwasham', stars: '264k', description: 'A complete computer science study plan to become a software engineer.' },
  { name: 'developer-roadmap', owner: 'kamranahmedse', stars: '244k', description: 'Roadmap to becoming a developer in 2023' },
  { name: 'awesome', owner: 'sindresorhus', stars: '263k', description: 'Awesome lists about all kinds of interesting topics' },
  { name: 'public-apis', owner: 'public-apis', stars: '248k', description: 'A collective list of free APIs for use in software and web development.' },
  { name: 'gitignore', owner: 'github', stars: '152k', description: 'A collection of useful .gitignore templates' },
  { name: 'You-Dont-Know-JS', owner: 'getify', stars: '170k', description: 'A book series on JavaScript. @YDKJS on twitter.' },
  { name: 'javascript', owner: 'airbnb', stars: '137k', description: 'JavaScript Style Guide' },
  { name: 'javascript-algorithms', owner: 'trekhleb', stars: '173k', description: 'Algorithms and data structures implemented in JavaScript with explanations and links to further readings' },
  { name: 'oh-my-zsh', owner: 'ohmyzsh', stars: '161k', description: 'A delightful community-driven framework for managing your zsh configuration.' },
  { name: 'the-art-of-command-line', owner: 'jlevy', stars: '133k', description: 'Master the command line, in one page' },
  { name: 'docker-ce', owner: 'docker', stars: '6.6k', description: 'Docker CE' },
  { name: 'linux-insides', owner: '0xAX', stars: '28.5k', description: 'A book-in-progress about the linux kernel' },
  { name: 'realworld', owner: 'gothinkster', stars: '75.8k', description: 'The mother of all demo apps — Exemplary fullstack Medium.com clone powered by React, Angular, Node, Django, and many more' },
  { name: 'electron', owner: 'electron', stars: '108k', description: 'Build cross-platform desktop apps with JavaScript, HTML, and CSS' },
  { name: 'ansible', owner: 'ansible', stars: '58k', description: 'Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain.' },
  { name: 'terraform', owner: 'hashicorp', stars: '38k', description: 'Terraform enables you to safely and predictably create, change, and improve infrastructure.' },
  { name: 'react-native', owner: 'facebook', stars: '111k', description: 'A framework for building native apps with React.' },
  { name: 'tailwindcss', owner: 'tailwindlabs', stars: '71k', description: 'A utility-first CSS framework for rapid UI development.' },
  { name: 'storybook', owner: 'storybookjs', stars: '80k', description: 'UI component dev environment for React, Vue, and Angular' },
  { name: 'jest', owner: 'facebook', stars: '42k', description: 'Delightful JavaScript Testing.' },
  { name: 'webpack', owner: 'webpack', stars: '63k', description: 'A bundler for javascript and friends.' },
  { name: 'babel', owner: 'babel', stars: '42k', description: 'Babel is a compiler for writing next generation JavaScript.' },
  { name: 'redis', owner: 'redis', stars: '61k', description: 'Redis is an in-memory database that persists on disk.' },
  { name: 'nginx', owner: 'nginx', stars: '18.8k', description: 'An official read-only mirror of http://hg.nginx.org/nginx/ which is updated hourly.' },
  { name: 'laravel', owner: 'laravel', stars: '74k', description: 'A PHP web application framework with expressive, elegant syntax.' },
  { name: 'django', owner: 'django', stars: '72k', description: 'The Web framework for perfectionists with deadlines.' },
  { name: 'flask', owner: 'pallets', stars: '64k', description: 'The Python micro framework for building web applications.' },
  { name: 'fastapi', owner: 'tiangolo', stars: '61k', description: 'FastAPI framework, high performance, easy to learn, fast to code, ready for production' },
  { name: 'kubernetes-handbook', owner: 'rootsongjc', stars: '15.6k', description: 'Kubernetes-handbook is a cloud-native application guide' },
  { name: 'system-design-primer', owner: 'donnemartin', stars: '226k', description: 'Learn how to design large-scale systems. Prep for the system design interview. Includes Anki flashcards.' },
  { name: 'build-your-own-x', owner: 'danistefanovic', stars: '173k', description: 'Build your own (insert technology here)' },
  { name: 'project-based-learning', owner: 'tuvtran', stars: '100k', description: 'A list of programming tutorials in which aspiring software developers learn how to build an application from scratch.' },
  { name: 'serverless', owner: 'serverless', stars: '45k', description: 'Serverless Framework – Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more!' },
  { name: 'helm-charts', owner: 'helm', stars: '17.6k', description: 'Curated applications for Kubernetes' },
  { name: 'prometheus', owner: 'prometheus', stars: '49k', description: 'The Prometheus monitoring system and time series database.' },
  { name: 'grafana', owner: 'grafana', stars: '56k', description: 'The open and composable observability and data visualization platform.' },
  { name: 'kibana', owner: 'elastic', stars: '18.7k', description: 'Your window into the Elastic Stack' },
  { name: 'elasticsearch', owner: 'elastic', stars: '65k', description: 'Free and Open, Distributed, RESTful Search Engine' },
  { name: 'logstash', owner: 'elastic', stars: '13.6k', description: 'Logstash - transport and process your logs, events, or other data' },
  { name: 'jenkins', owner: 'jenkinsci', stars: '21k', description: 'Jenkins automation server' },
  { name: 'home-assistant', owner: 'home-assistant', stars: '62k', description: 'Open source home automation that puts local control and privacy first.' },
  { name: 'shadowsocks', owner: 'shadowsocks', stars: '33.6k', description: 'A secure socks5 proxy' },
  { name: 'ohmytmux', owner: 'gpakosz', stars: '19.8k', description: 'Oh My Tmux! Pretty & versatile tmux configuration made with love' },
  { name: 'powerlevel10k', owner: 'romkatv', stars: '37.8k', description: 'A Zsh theme' },
  { name: 'neovim', owner: 'neovim', stars: '67k', description: 'Vim-fork focused on extensibility and usability' },
  { name: 'atom', owner: 'atom', stars: '59.3k', description: 'The hackable text editor' },
  { name: 'sublime-text', owner: 'sublimehq', stars: '1.2k', description: 'Issue tracker for Sublime Text' }
]; 