import { Metadata } from 'next';
import { createCaller } from '@/lib/trpc/server';
import { auth } from '@/lib/auth';
import { createGitHubServiceForUserOperations } from '@/lib/github';
import { headers } from 'next/headers';
import { WikiIndexClient } from './WikiIndexClient';
import { createLogger } from '@/lib/logging';

const logger = createLogger('WikiPermissionCheck');

export const dynamicParams = true;

interface WikiIndexProps {
  params: Promise<{
    owner: string;
    repo: string;
  }>;
  searchParams: Promise<{
    version?: string;
  }>;
}

// Generate metadata for SEO
export async function generateMetadata({ params }: WikiIndexProps): Promise<Metadata> {
  const { owner, repo } = await params;

  const title = `${owner}/${repo} Documentation Wiki`;
  const description = `Comprehensive documentation and API reference for ${owner}/${repo}, auto-generated by gh.gg`;

  return {
    title,
    description,
    keywords: [owner, repo, 'documentation', 'wiki', 'API reference', 'developer docs'],
    openGraph: {
      title,
      description,
      type: 'website',
      url: `https://github.gg/wiki/${owner}/${repo}`,
      siteName: 'gh.gg',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
    robots: {
      index: true,
      follow: true,
    },
  };
}

export default async function WikiIndex({ params, searchParams }: WikiIndexProps) {
  const { owner, repo } = await params;
  const { version } = await searchParams;

  const caller = await createCaller();
  const [toc, branchesResult, repoInfoResult] = await Promise.all([
    caller.wiki.getWikiTableOfContents({
      owner,
      repo,
      version: version ? parseInt(version) : undefined,
    }),
    caller.github.getBranches({ owner, repo }).catch(() => undefined),
    caller.github.getRepoInfo({ owner, repo }).catch(() => undefined),
  ]);

  const branches = branchesResult || [];
  const defaultBranch = repoInfoResult?.defaultBranch || 'main';

  // Check if user has permission to edit/delete wiki
  let canEditWiki = false;
  try {
    const headersList = await headers();
    const session = await auth.api.getSession({ headers: headersList } as Request);
    if (session?.user) {
      const githubService = await createGitHubServiceForUserOperations(session);
      const { data: repoData } = await githubService['octokit'].repos.get({
        owner,
        repo,
      });
      canEditWiki = !!(repoData.permissions?.admin || repoData.permissions?.push);
    }
  } catch (error) {
    logger.error('Failed to check repository permissions', error);
  }

  const wikiPages = toc?.pages.map(p => ({ slug: p.slug, title: p.title })) || [];

  return (
    <WikiIndexClient
      owner={owner}
      repo={repo}
      version={version ? parseInt(version) : undefined}
      toc={toc}
      branches={branches}
      defaultBranch={defaultBranch}
      canEditWiki={canEditWiki}
      wikiPages={wikiPages}
    />
  );
}
